development:
  adapter: mysql2
  encoding: utf8
  database: asam
  pool: 5
  username: asam
  password: eZE34K9ZQ9CL5HR6
  host: localhost
  collation: utf8_unicode_ci

test:
  adapter: mysql2
  database: asam
  username: root
  encoding: utf8
  collation: utf8_unicode_ci

production:
  adapter: mysql2
  encoding: utf8
  database: asam
  pool: 5
  username: asam
  password: eZE34K9ZQ9CL5HR6
  host: localhost
  collation: utf8_unicode_ci