# Place this file into config folder of your RailsRoot
api-key: '5aa9f7c9-16e5-48f3-b400-e9e556494222'
development:
 enabled: false
production:
  enabled: true
staging:
  api-key: '5aa9f7c9-16e5-48f3-b400-e9e556494222' # You can change if you have create different project
  enabled: true
